### ISSUE TITLE
Typo in "About" and README section of repo

### ISSUE THREAD

**Issue by PythonTryHard** [Kowlin/Sentinel#30]
It should be "oriented" not "orianted". And should there be a `-` between "moderation" and "oriented"? I'm not solid on English

**Comment by Jackenmen** [comment]
While we're at typos in the About sidebar, there's also "build" in that section rather than "built"

**Comment by Kowlin** [comment]
*eyerolls* Fair enough... that's on me for writing a quickly wrote readme!

**Comment by Kowlin** [comment]
Closed in https://github.com/Kowlin/Sentinel/commit/2439bb6edfd24b594c41e7ba06b82d111eed24c9
